-- Day 03 core persistence schema.
-- Public IDs are generated by the application as UUID strings.

CREATE TABLE users (
  id TEXT PRIMARY KEY,
  email TEXT,
  display_name TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE documents (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  source_kind TEXT NOT NULL CHECK (source_kind IN ('paste', 'file', 'pdf')),
  source_ref TEXT,
  goal TEXT NOT NULL,
  status TEXT NOT NULL CHECK (
    status IN ('draft', 'uploaded', 'parsed', 'chunked', 'cards_generated', 'failed')
  ),
  content_hash TEXT,
  word_count INTEGER NOT NULL DEFAULT 0 CHECK (word_count >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  parsed_at TIMESTAMPTZ,
  failed_at TIMESTAMPTZ,
  failure_reason TEXT
);

CREATE TABLE document_chunks (
  id TEXT PRIMARY KEY,
  document_id TEXT NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
  sequence INTEGER NOT NULL CHECK (sequence >= 0),
  citation TEXT NOT NULL,
  text TEXT NOT NULL,
  topics_json TEXT NOT NULL DEFAULT '[]',
  token_estimate INTEGER NOT NULL DEFAULT 0 CHECK (token_estimate >= 0),
  embedding_status TEXT NOT NULL DEFAULT 'pending' CHECK (
    embedding_status IN ('pending', 'embedded', 'failed', 'skipped')
  ),
  embedding_provider TEXT,
  embedding_model TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (document_id, sequence)
);

CREATE TABLE study_sessions (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  document_id TEXT NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
  goal TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('building', 'ready', 'archived', 'failed')),
  generation_mode TEXT NOT NULL CHECK (generation_mode IN ('fallback', 'ai', 'preview')),
  model TEXT NOT NULL,
  focus_tags_json TEXT NOT NULL DEFAULT '[]',
  stats_json TEXT NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ready_at TIMESTAMPTZ,
  failed_at TIMESTAMPTZ,
  failure_reason TEXT
);

CREATE TABLE study_cards (
  id TEXT PRIMARY KEY,
  session_id TEXT NOT NULL REFERENCES study_sessions(id) ON DELETE CASCADE,
  document_id TEXT NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
  chunk_id TEXT REFERENCES document_chunks(id) ON DELETE SET NULL,
  sequence INTEGER NOT NULL CHECK (sequence >= 0),
  kind TEXT NOT NULL CHECK (kind IN ('glance', 'recall', 'application', 'pitfall')),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'saved', 'dismissed')),
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  question TEXT,
  answer TEXT,
  excerpt TEXT NOT NULL,
  citation TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (session_id, sequence)
);

CREATE TABLE study_interactions (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  session_id TEXT NOT NULL REFERENCES study_sessions(id) ON DELETE CASCADE,
  card_id TEXT REFERENCES study_cards(id) ON DELETE SET NULL,
  interaction_type TEXT NOT NULL CHECK (
    interaction_type IN (
      'reveal_answer',
      'save_card',
      'unsave_card',
      'set_confidence',
      'dismiss_card'
    )
  ),
  value TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX documents_user_status_idx ON documents(user_id, status, updated_at DESC);
CREATE INDEX document_chunks_document_sequence_idx ON document_chunks(document_id, sequence);
CREATE INDEX study_sessions_user_created_idx ON study_sessions(user_id, created_at DESC);
CREATE INDEX study_cards_session_sequence_idx ON study_cards(session_id, sequence);
CREATE INDEX study_interactions_user_session_idx ON study_interactions(user_id, session_id, created_at DESC);
